### ISSUE TITLE
Allow partial “best effort” compilation

### ISSUE THREAD

**Issue by Ikyushii** [ogma-project/ogmarkup#19]
Can this be a parameter of the generator?

Anyway it may be a good idea to improve the user experience, for instance to have preview even if the document has some errors in it (and it will have some eventually).

**Comment by Ikyushii** [comment]
@lgeorget do you have any idea about this? I want to avoid as far as possible to modify the `Ast` datatype for this.

**Comment by lgeorget** [comment]
The usual way to do it in compilers is having "resynchronization points", i.e. points in the parsing process where we are sure that we are in a correct and known state. In our case, a good candidate for this would be the beginning of a paragraph.

**Comment by Ikyushii** [comment]
Do we have to modify the AST accordingly? I would rather not, yet  maybe it is a good way to deal with errors, I don’t really know.

**Comment by lgeorget** [comment]
I think you can use the same AST, but you have to encapsulate the return values in the AST with a monad that can "resynchronize" on errors.
