### ISSUE TITLE
Cannot parse a valid dialogue

### ISSUE THREAD

**Issue by Ikyushii** [ogma-project/ogmarkup#28]
```
[Pourquoi tu es partie?| demanda précipitemment l'enfant.|]
```

**Comment by lgeorget** [comment]
Apparently, the space before "demanda" causes the issue. Without this space, the line is parsed correctly.

**Comment by Ikyushii** [comment]
Add a call to the `blank` monad should solve this. We can use this opportunity to enforce some new policy: whenever we solve a bug, we add a test to check if the fix is correct.
